import { useCallback, useMemo, useState, type ReactNode } from "react";
import logoSvgPath from "../../favicon.svg" with { type: "file" };
import {
  useToast,
  WebAppRoot,
  type WebAppRoute,
} from "@pablozaiden/webapp/web";
import {
  buildShellRoutes,
  type ShellRouteCompositionContext,
} from "./shell-route-composition";
import {
  buildShellSidebarComposition,
  type ShellSidebarActionHandlers,
} from "./shell-sidebar-composition";
import { buildShellSettingsSections } from "./shell-settings-composition";
import { ShellHeaderActionsContext } from "./shell-header-actions";
import { useShellActions } from "./use-shell-actions";
import { HOME_ROUTE, useShellNavigation } from "./use-shell-navigation";
import {
  RouteHeaderTitle,
  useShellHeader,
  type RegisteredHeaderActions,
} from "./use-shell-header";
import { useShellResources } from "./use-shell-resources";

export function AppShell() {
  const toast = useToast();
  const [route, setRoute] = useState<WebAppRoute>(HOME_ROUTE);
  const [registeredHeaderActions, setRegisteredHeaderActions] = useState<RegisteredHeaderActions | null>(null);
  const registerHeaderActions = useCallback((owner: symbol, actions: ReactNode) => {
    setRegisteredHeaderActions({ owner, actions });
  }, []);
  const unregisterHeaderActions = useCallback((owner: symbol) => {
    setRegisteredHeaderActions((current) => current?.owner === owner ? null : current);
  }, []);
  const shellHeaderActionsContextValue = useMemo(
    () => ({ register: registerHeaderActions, unregister: unregisterHeaderActions }),
    [registerHeaderActions, unregisterHeaderActions],
  );
  const {
    chats,
    chatsLoading,
    refreshChats,
    createChat,
    importExistingChat,
    createSshServerChat,
    updateChat,
    markChatDone,
    deleteChat,
    agents,
    tasks,
    tasksLoading,
    refreshTasks,
    markTaskStarting,
    clearOptimisticTaskStart,
    createTask,
    updateTask,
    purgeTask,
    purgeArchivedWorkspaceTasks,
    terminalSessions,
    executionHosts,
    refreshExecutionHosts,
    createTerminalSession,
    updateTerminalSession,
    deleteTerminalSession,
    servers,
    sessionsByServerId,
    refreshSshServers,
    createServer,
    updateServer,
    deleteServer,
    createStandaloneSession,
    updateStandaloneSession,
    deleteStandaloneSession,
    workspaces,
    workspacesLoading,
    workspacesSaving,
    workspaceError,
    refreshWorkspaces,
    createWorkspace,
    updateWorkspace,
    deleteWorkspace,
    pullLatestChanges,
    quickChatSettings,
    schedulerTimezone,
    markdownPreference,
    mesh,
    fullTreePreference,
    privateItemsPreference,
    dashboardData,
    provisioning,
    workspaceGroups,
    allWorkspaceGroups,
    sidebarWorkspaceGroups,
    serverNodes,
    quickChatWorkspace,
    quickChatUnavailableReason,
    shellLoading,
    shellErrors,
    taskId,
    chatId,
    composeKind,
    selectedTask,
    selectedChat,
    selectedWorkspace,
    selectedServer,
    composeWorkspace,
    composeServer,
    composeExecutionHost,
    selectedAgent,
  } = useShellResources(route);

  const {
    webAppRootRef,
    handleWebRouteChange,
    navigateWithinShell,
  } = useShellNavigation({
    setRoute,
  });

  const {
    workspaceCreate,
    workspaceSettings,
    composeState,
    selectedChatActions,
    dialogs,
    pullingLatestWorkspaceIds,
    archivingWorkspaceIds,
    pullLatestWorkspaceChanges,
    toggleWorkspaceArchived,
    handleSidebarMarkChatDone,
    toggleTaskPrivate,
    toggleChatPrivate,
    toggleAgentPrivate,
    toggleWorkspacePrivate,
    toggleTerminalSessionPrivate,
    toggleSshServerPrivate,
    toggleStandaloneSshSessionPrivate,
    stopSidebarTask,
  } = useShellActions({
    route,
    navigateWithinShell,
    servers,
    provisioning,
    createWorkspace,
    refreshWorkspaces,
    workspaceGroups: allWorkspaceGroups,
    purgeArchivedWorkspaceTasks,
    pullLatestChanges,
    updateWorkspace,
    createTask,
    refreshTasks,
    dashboardData,
    toast,
    markChatDone,
    deleteChat,
    selectedChat,
    refreshChats,
    updateChat,
    agents,
    updateTask,
    updateStandaloneSession,
    updateServer,
    refreshSshServers,
    updateTerminalSession,
    deleteTerminalSession,
    deleteStandaloneSession,
    createChat,
    quickChatSettings,
    quickChatWorkspace,
  });

  const routes = useMemo(() => buildShellRoutes({
    shellLoading,
    shellErrors,
    navigateWithinShell,
    tasks,
    chats,
    workspaces,
    terminalSessions,
    executionHosts,
    servers,
    sessionsByServerId,
    serverNodes,
    workspaceGroups,
    sidebarWorkspaceGroups,
    workspacesLoading,
    workspacesSaving,
    workspaceError,
    refreshTasks,
    markTaskStarting,
    clearOptimisticTaskStart,
    refreshChats,
    purgeTask,
    refreshSshServers,
    refreshExecutionHosts,
    refreshWorkspaces,
    createTerminalSession,
    createStandaloneSession,
    createServer,
    updateServer,
    deleteServer,
    deleteWorkspace,
    dashboardData,
    schedulerTimezone: schedulerTimezone.timezone,
    agents,
    editingAgentId: dialogs.editingAgentId,
    onCancelAgentEdit: dialogs.cancelAgentEdit,
    onSavedAgentEdit: dialogs.handleAgentSaved,
    composeActionState: composeState.composeActionState,
    setComposeActionState: composeState.setComposeActionState,
    handleTaskSubmit: composeState.handleTaskSubmit,
    createChat,
    importExistingChat,
    createSshServerChat,
    workspaceCreate,
    workspaceSettings,
    provisioning,
    toast,
    showPrivateItems: privateItemsPreference.showPrivateItems,
  } satisfies ShellRouteCompositionContext), [
    agents,
    dialogs.cancelAgentEdit,
    chats,
    composeState.composeActionState,
    composeState.handleTaskSubmit,
    composeState.setComposeActionState,
    createChat,
    createServer,
    createSshServerChat,
    createStandaloneSession,
    createTerminalSession,
    dashboardData,
    deleteServer,
    deleteWorkspace,
    dialogs.editingAgentId,
    dialogs.handleAgentSaved,
    importExistingChat,
    navigateWithinShell,
    privateItemsPreference.showPrivateItems,
    provisioning,
    purgeTask,
    refreshChats,
    refreshExecutionHosts,
    refreshSshServers,
    refreshTasks,
    markTaskStarting,
    clearOptimisticTaskStart,
    refreshWorkspaces,
    schedulerTimezone.timezone,
    serverNodes,
    servers,
    sessionsByServerId,
    shellErrors,
    shellLoading,
    sidebarWorkspaceGroups,
    tasks,
    terminalSessions,
    executionHosts,
    toast,
    updateServer,
    workspaceCreate,
    workspaceError,
    workspaceGroups,
    workspaceSettings,
    workspaces,
    workspacesLoading,
    workspacesSaving,
  ]);

  const settingsSections = useMemo(() => buildShellSettingsSections({
    quickChatSettings,
    schedulerTimezone,
    markdownPreference,
    fullTreePreference,
    privateItemsPreference,
    dashboardData,
    workspaces,
    workspacesLoading,
    refreshTasks,
    mesh,
  }), [
    dashboardData,
    fullTreePreference,
    markdownPreference,
    mesh,
    privateItemsPreference,
    quickChatSettings,
    refreshTasks,
    schedulerTimezone,
    workspaces,
    workspacesLoading,
  ]);

  const sidebarSnapshotReady = !shellLoading && shellErrors.length === 0;
  const sidebarComposition = useMemo(() => buildShellSidebarComposition({
    sidebarWorkspaceGroups,
    serverNodes,
    executionHosts,
    chats,
    terminalSessions,
    workspaces,
    agents: agents.agents,
    handlers: {
      route,
      selectedChat,
      selectedChatActions,
      navigateWithinShell,
      onError: (message) => toast.error(message),
      toggleTaskPrivate,
      toggleChatPrivate,
      markChatDone: handleSidebarMarkChatDone,
      toggleAgentPrivate,
      toggleWorkspacePrivate,
      toggleTerminalSessionPrivate,
      toggleSshServerPrivate,
      toggleStandaloneSshSessionPrivate,
      stopSidebarTask,
      openRenameStandaloneSshSession: dialogs.openRenameStandaloneSshSession,
      openDeleteStandaloneSshSession: dialogs.openDeleteStandaloneSshSession,
      openRenameTerminalSession: dialogs.openRenameTerminalSession,
      openDeleteTerminalSession: dialogs.openDeleteTerminalSession,
      pullLatestWorkspaceChanges,
      pullingLatestWorkspaceIds,
      toggleWorkspaceArchived,
      archivingWorkspaceIds,
      setEditingAgentId: dialogs.setEditingAgentId,
      setDeleteAgentTarget: dialogs.setDeleteAgentTarget,
      setPurgeAgentTarget: dialogs.setPurgeAgentTarget,
      agents,
      showPrivateItems: privateItemsPreference.showPrivateItems,
    } satisfies ShellSidebarActionHandlers,
    sidebarSnapshotReady,
    quickChatUnavailableReason,
    quickChatCreating: dialogs.quickChatCreating,
    onQuickChat: () => void dialogs.handleQuickChat(),
  }), [
    agents,
    archivingWorkspaceIds,
    dialogs.handleQuickChat,
    navigateWithinShell,
    dialogs.openDeleteStandaloneSshSession,
    dialogs.openDeleteTerminalSession,
    dialogs.openRenameStandaloneSshSession,
    dialogs.openRenameTerminalSession,
    privateItemsPreference.showPrivateItems,
    pullLatestWorkspaceChanges,
    pullingLatestWorkspaceIds,
    dialogs.quickChatCreating,
    quickChatUnavailableReason,
    route,
    selectedChat,
    selectedChatActions,
    serverNodes,
    sidebarSnapshotReady,
    dialogs.setDeleteAgentTarget,
    dialogs.setEditingAgentId,
    dialogs.setPurgeAgentTarget,
    executionHosts,
    sidebarWorkspaceGroups,
    stopSidebarTask,
    toast,
    toggleAgentPrivate,
    toggleChatPrivate,
    handleSidebarMarkChatDone,
    toggleSshServerPrivate,
    toggleStandaloneSshSessionPrivate,
    toggleTaskPrivate,
    toggleTerminalSessionPrivate,
    toggleWorkspaceArchived,
    toggleWorkspacePrivate,
    workspaces,
  ]);
  const header = useShellHeader({
    route,
    headerNodes: sidebarComposition.headerNodes,
    registeredHeaderActions,
    navigateWithinShell,
    taskId,
    chatId,
    composeKind,
    selectedTask,
    selectedChat,
    selectedWorkspace,
    composeWorkspace,
    composeServer,
    composeExecutionHost,
    selectedServer,
    selectedAgent,
    tasksLoading,
    chatsLoading,
    agents,
    servers,
    terminalSessions,
    sessionsByServerId,
    workspaces,
    editingAgentId: dialogs.editingAgentId,
    composeActionState: composeState.composeActionState,
  });

  return (
    <ShellHeaderActionsContext.Provider value={shellHeaderActionsContextValue}>
      <WebAppRoot
        ref={webAppRootRef}
        appName="Clanky"
        appIcon={logoSvgPath}
        homeRoute={HOME_ROUTE}
        sidebar={sidebarComposition.sidebar}
        routes={routes}
        onRouteChange={handleWebRouteChange}
        header={{
          renderTitle: ({ defaultTitle }) => <RouteHeaderTitle model={header.headerModel} defaultTitle={defaultTitle} />,
          renderActions: () => header.directHeaderActions,
          getActions: () => header.headerActions,
        }}
        settings={{ sections: settingsSections }}
        version={dashboardData.version ?? undefined}
      />
      {dialogs.modals}
    </ShellHeaderActionsContext.Provider>
  );
}

export default AppShell;
