-- Demo-only UI seed for local visual testing.
-- Apply this against data/clanky.db with your preferred SQLite client.

PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;

INSERT INTO webapp_users (
  id,
  username,
  role,
  auth_version,
  created_at,
  updated_at,
  last_login_at,
  disabled_at
) VALUES (
  'admin',
  'admin',
  'owner',
  1,
  '2026-04-16T18:00:00.000Z',
  '2026-04-16T18:00:00.000Z',
  NULL,
  NULL
)
ON CONFLICT(id) DO UPDATE SET
  username = excluded.username,
  role = excluded.role,
  auth_version = excluded.auth_version,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  last_login_at = excluded.last_login_at,
  disabled_at = excluded.disabled_at;

INSERT INTO ssh_servers (
  id,
  name,
  address,
  username,
  created_at,
  updated_at,
  repositories_base_path
) VALUES (
  'demo-server-build',
  'Build Box',
  'demo-box.internal',
  'clanky',
  '2026-04-16T18:00:00.000Z',
  '2026-04-16T18:00:00.000Z',
  '/srv/workspaces'
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  address = excluded.address,
  username = excluded.username,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  repositories_base_path = excluded.repositories_base_path;

INSERT INTO ssh_servers (
  id,
  name,
  address,
  username,
  created_at,
  updated_at,
  repositories_base_path
) VALUES (
  'demo-server-ops',
  'Ops Box',
  'ops-box.internal',
  'deploy',
  '2026-04-16T18:05:00.000Z',
  '2026-04-16T18:05:00.000Z',
  '/opt/projects'
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  address = excluded.address,
  username = excluded.username,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  repositories_base_path = excluded.repositories_base_path;

INSERT INTO ssh_server_sessions (
  id,
  ssh_server_id,
  name,
  remote_session_name,
  created_at,
  updated_at,
  status,
  last_connected_at,
  error_message,
  connection_mode,
  runtime_connection_mode,
  notice_message
) VALUES (
  'demo-server-session-build-main',
  'demo-server-build',
  'Main shell',
  'clanky-build-main',
  '2026-04-16T18:10:00.000Z',
  '2026-04-16T19:30:00.000Z',
  'connected',
  '2026-04-16T19:30:00.000Z',
  NULL,
  'dtach',
  NULL,
  'Attached to persistent shell.'
)
ON CONFLICT(id) DO UPDATE SET
  ssh_server_id = excluded.ssh_server_id,
  name = excluded.name,
  remote_session_name = excluded.remote_session_name,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  status = excluded.status,
  last_connected_at = excluded.last_connected_at,
  error_message = excluded.error_message,
  connection_mode = excluded.connection_mode,
  runtime_connection_mode = excluded.runtime_connection_mode,
  notice_message = excluded.notice_message;

INSERT INTO ssh_server_sessions (
  id,
  ssh_server_id,
  name,
  remote_session_name,
  created_at,
  updated_at,
  status,
  last_connected_at,
  error_message,
  connection_mode,
  runtime_connection_mode,
  notice_message
) VALUES (
  'demo-server-session-ops-debug',
  'demo-server-ops',
  'Debug shell',
  'clanky-ops-debug',
  '2026-04-16T18:15:00.000Z',
  '2026-04-16T19:20:00.000Z',
  'failed',
  '2026-04-16T19:18:00.000Z',
  'SSH handshake timed out after key exchange.',
  'direct',
  NULL,
  'Reconnect to retry the direct shell.'
)
ON CONFLICT(id) DO UPDATE SET
  ssh_server_id = excluded.ssh_server_id,
  name = excluded.name,
  remote_session_name = excluded.remote_session_name,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  status = excluded.status,
  last_connected_at = excluded.last_connected_at,
  error_message = excluded.error_message,
  connection_mode = excluded.connection_mode,
  runtime_connection_mode = excluded.runtime_connection_mode,
  notice_message = excluded.notice_message;

INSERT INTO workspaces (
  id,
  name,
  directory,
  server_fingerprint,
  created_at,
  updated_at,
  server_settings,
  source_directory,
  ssh_server_id,
  repo_url,
  base_path,
  devcontainer_subpath,
  provider
) VALUES (
  'demo-workspace-webapp',
  'Storefront Web',
  '/workspaces/demo-storefront',
  'opencode:stdio',
  '2026-04-16T17:50:00.000Z',
  '2026-04-16T19:40:00.000Z',
  '{"agent":{"provider":"opencode","transport":"stdio"}}',
  NULL,
  NULL,
  'https://github.com/example/demo-storefront',
  NULL,
  NULL,
  'opencode'
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  directory = excluded.directory,
  server_fingerprint = excluded.server_fingerprint,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  server_settings = excluded.server_settings,
  source_directory = excluded.source_directory,
  ssh_server_id = excluded.ssh_server_id,
  repo_url = excluded.repo_url,
  base_path = excluded.base_path,
  devcontainer_subpath = excluded.devcontainer_subpath,
  provider = excluded.provider;

INSERT INTO workspaces (
  id,
  name,
  directory,
  server_fingerprint,
  created_at,
  updated_at,
  server_settings,
  source_directory,
  ssh_server_id,
  repo_url,
  base_path,
  devcontainer_subpath,
  provider
) VALUES (
  'demo-workspace-api',
  'Billing API',
  '/srv/workspaces/billing-api',
  'copilot:ssh:demo-box.internal:22:clanky',
  '2026-04-16T17:55:00.000Z',
  '2026-04-16T19:45:00.000Z',
  '{"agent":{"provider":"copilot","transport":"ssh","hostname":"demo-box.internal","port":22,"username":"clanky"}}',
  '/srv/workspaces',
  'demo-server-build',
  'https://github.com/example/billing-api',
  '/srv/workspaces',
  '.devcontainer/api',
  'copilot'
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  directory = excluded.directory,
  server_fingerprint = excluded.server_fingerprint,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  server_settings = excluded.server_settings,
  source_directory = excluded.source_directory,
  ssh_server_id = excluded.ssh_server_id,
  repo_url = excluded.repo_url,
  base_path = excluded.base_path,
  devcontainer_subpath = excluded.devcontainer_subpath,
  provider = excluded.provider;

INSERT INTO agents (
  id,
  name,
  workspace_id,
  directory,
  prompt,
  model_provider_id,
  model_model_id,
  model_variant,
  base_branch,
  use_worktree,
  schedule_start_at_local,
  schedule_timezone,
  schedule_interval_value,
  schedule_interval_unit,
  schedule_next_run_at,
  enabled,
  mode,
  created_at,
  updated_at,
  status,
  last_run_at,
  next_run_at,
  last_skipped_at,
  last_error_message,
  last_error_timestamp,
  last_error_code,
  active_run_id
) VALUES (
  'demo-agent-billing-review',
  'Billing risk review',
  'demo-workspace-api',
  '/srv/workspaces/billing-api',
  'Review recent billing changes and summarize risks for the team.',
  'openai',
  'gpt-5.2',
  '',
  'main',
  1,
  '2026-04-17T09:00',
  'America/New_York',
  1,
  'days',
  '2026-07-17T13:00:00.000Z',
  0,
  'agent',
  '2026-04-16T18:20:00.000Z',
  '2026-04-16T19:10:00.000Z',
  'paused',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  workspace_id = excluded.workspace_id,
  directory = excluded.directory,
  prompt = excluded.prompt,
  model_provider_id = excluded.model_provider_id,
  model_model_id = excluded.model_model_id,
  model_variant = excluded.model_variant,
  base_branch = excluded.base_branch,
  use_worktree = excluded.use_worktree,
  schedule_start_at_local = excluded.schedule_start_at_local,
  schedule_timezone = excluded.schedule_timezone,
  schedule_interval_value = excluded.schedule_interval_value,
  schedule_interval_unit = excluded.schedule_interval_unit,
  schedule_next_run_at = excluded.schedule_next_run_at,
  enabled = excluded.enabled,
  mode = excluded.mode,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  status = excluded.status,
  last_run_at = excluded.last_run_at,
  next_run_at = excluded.next_run_at,
  last_skipped_at = excluded.last_skipped_at,
  last_error_message = excluded.last_error_message,
  last_error_timestamp = excluded.last_error_timestamp,
  last_error_code = excluded.last_error_code,
  active_run_id = excluded.active_run_id;

INSERT INTO agents (
  id,
  name,
  workspace_id,
  directory,
  prompt,
  model_provider_id,
  model_model_id,
  model_variant,
  base_branch,
  use_worktree,
  schedule_start_at_local,
  schedule_timezone,
  schedule_interval_value,
  schedule_interval_unit,
  schedule_next_run_at,
  enabled,
  mode,
  created_at,
  updated_at,
  status,
  last_run_at,
  next_run_at,
  last_skipped_at,
  last_error_message,
  last_error_timestamp,
  last_error_code,
  active_run_id
) VALUES (
  'demo-agent-storefront-a11y',
  'Storefront accessibility sweep',
  'demo-workspace-webapp',
  '/workspaces/demo-storefront',
  'Inspect the storefront for accessibility regressions and report actionable findings.',
  'anthropic',
  'claude-sonnet-4.5',
  '',
  'main',
  1,
  '2026-04-17T14:30',
  'Europe/Madrid',
  12,
  'hours',
  '2026-07-17T12:30:00.000Z',
  0,
  'agent',
  '2026-04-16T18:25:00.000Z',
  '2026-04-16T19:15:00.000Z',
  'paused',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  workspace_id = excluded.workspace_id,
  directory = excluded.directory,
  prompt = excluded.prompt,
  model_provider_id = excluded.model_provider_id,
  model_model_id = excluded.model_model_id,
  model_variant = excluded.model_variant,
  base_branch = excluded.base_branch,
  use_worktree = excluded.use_worktree,
  schedule_start_at_local = excluded.schedule_start_at_local,
  schedule_timezone = excluded.schedule_timezone,
  schedule_interval_value = excluded.schedule_interval_value,
  schedule_interval_unit = excluded.schedule_interval_unit,
  schedule_next_run_at = excluded.schedule_next_run_at,
  enabled = excluded.enabled,
  mode = excluded.mode,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  status = excluded.status,
  last_run_at = excluded.last_run_at,
  next_run_at = excluded.next_run_at,
  last_skipped_at = excluded.last_skipped_at,
  last_error_message = excluded.last_error_message,
  last_error_timestamp = excluded.last_error_timestamp,
  last_error_code = excluded.last_error_code,
  active_run_id = excluded.active_run_id;

INSERT INTO agents (
  id,
  name,
  workspace_id,
  directory,
  prompt,
  model_provider_id,
  model_model_id,
  model_variant,
  base_branch,
  use_worktree,
  schedule_start_at_local,
  schedule_timezone,
  schedule_interval_value,
  schedule_interval_unit,
  schedule_next_run_at,
  enabled,
  mode,
  created_at,
  updated_at,
  status,
  last_run_at,
  next_run_at,
  last_skipped_at,
  last_error_message,
  last_error_timestamp,
  last_error_code,
  active_run_id
) VALUES (
  'demo-agent-release-notes',
  'Release notes watcher',
  'demo-workspace-webapp',
  '/workspaces/demo-storefront',
  'Track release-facing changes and prepare a concise draft of the weekly notes.',
  'copilot',
  'gpt-5.4',
  'medium',
  'main',
  0,
  '2026-04-18T10:00',
  'UTC',
  7,
  'days',
  '2026-07-18T10:00:00.000Z',
  0,
  'agent',
  '2026-04-16T18:30:00.000Z',
  '2026-04-16T19:20:00.000Z',
  'paused',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  workspace_id = excluded.workspace_id,
  directory = excluded.directory,
  prompt = excluded.prompt,
  model_provider_id = excluded.model_provider_id,
  model_model_id = excluded.model_model_id,
  model_variant = excluded.model_variant,
  base_branch = excluded.base_branch,
  use_worktree = excluded.use_worktree,
  schedule_start_at_local = excluded.schedule_start_at_local,
  schedule_timezone = excluded.schedule_timezone,
  schedule_interval_value = excluded.schedule_interval_value,
  schedule_interval_unit = excluded.schedule_interval_unit,
  schedule_next_run_at = excluded.schedule_next_run_at,
  enabled = excluded.enabled,
  mode = excluded.mode,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  status = excluded.status,
  last_run_at = excluded.last_run_at,
  next_run_at = excluded.next_run_at,
  last_skipped_at = excluded.last_skipped_at,
  last_error_message = excluded.last_error_message,
  last_error_timestamp = excluded.last_error_timestamp,
  last_error_code = excluded.last_error_code,
  active_run_id = excluded.active_run_id;

INSERT INTO ssh_sessions (
  id,
  name,
  workspace_id,
  directory,
  remote_session_name,
  created_at,
  updated_at,
  status,
  last_connected_at,
  error_message,
  task_id,
  connection_mode,
  runtime_connection_mode,
  notice_message
) VALUES (
  'demo-workspace-session-api',
  'Workspace terminal',
  'demo-workspace-api',
  '/srv/workspaces/billing-api',
  'billing-api-terminal',
  '2026-04-16T18:25:00.000Z',
  '2026-04-16T19:35:00.000Z',
  'connected',
  '2026-04-16T19:35:00.000Z',
  NULL,
  NULL,
  'dtach',
  NULL,
  'Ready for a new terminal tab.'
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  workspace_id = excluded.workspace_id,
  directory = excluded.directory,
  remote_session_name = excluded.remote_session_name,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  status = excluded.status,
  last_connected_at = excluded.last_connected_at,
  error_message = excluded.error_message,
  task_id = excluded.task_id,
  connection_mode = excluded.connection_mode,
  runtime_connection_mode = excluded.runtime_connection_mode,
  notice_message = excluded.notice_message;

INSERT INTO ssh_sessions (
  id,
  name,
  workspace_id,
  directory,
  remote_session_name,
  created_at,
  updated_at,
  status,
  last_connected_at,
  error_message,
  task_id,
  connection_mode,
  runtime_connection_mode,
  notice_message
) VALUES (
  'demo-workspace-session-task-running',
  'Task shell',
  'demo-workspace-api',
  '/srv/worktrees/billing-api/running-task',
  'billing-api-task-running',
  '2026-04-16T18:30:00.000Z',
  '2026-04-16T19:32:00.000Z',
  'connected',
  '2026-04-16T19:32:00.000Z',
  NULL,
  'demo-task-running',
  'dtach',
  NULL,
  'Bound to the running task worktree.'
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  workspace_id = excluded.workspace_id,
  directory = excluded.directory,
  remote_session_name = excluded.remote_session_name,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  status = excluded.status,
  last_connected_at = excluded.last_connected_at,
  error_message = excluded.error_message,
  task_id = excluded.task_id,
  connection_mode = excluded.connection_mode,
  runtime_connection_mode = excluded.runtime_connection_mode,
  notice_message = excluded.notice_message;

INSERT INTO tasks (
  id,
  name,
  directory,
  prompt,
  created_at,
  updated_at,
  workspace_id,
  model_provider_id,
  model_model_id,
  model_variant,
  cheap_model,
  max_iterations,
  max_consecutive_errors,
  activity_timeout_seconds,
  stop_pattern,
  git_branch_prefix,
  git_commit_scope,
  base_branch,
  use_worktree,
  clear_planning_folder,
  plan_mode,
  plan_mode_auto_reply,
  auto_accept_plan,
  fully_autonomous,
  mode,
  status,
  current_iteration,
  started_at,
  completed_at,
  last_activity_at,
  session_id,
  session_server_url,
  error_message,
  error_iteration,
  error_timestamp,
  git_original_branch,
  git_working_branch,
  git_worktree_path,
  git_commits,
  recent_iterations,
  logs,
  messages,
  tool_calls,
  consecutive_errors,
  pending_prompt,
  pending_model_provider_id,
  pending_model_model_id,
  pending_model_variant,
  plan_mode_active,
  plan_session_id,
  plan_server_url,
  plan_feedback_rounds,
  plan_content,
  planning_folder_cleared,
  plan_is_ready,
  pending_plan_question,
  review_mode,
  pull_request_monitoring,
  automatic_pr_flow,
  fully_autonomous_pending
) VALUES (
  'demo-task-planning',
  'Dashboard filters',
  '/workspaces/demo-storefront',
  'Design and implement dashboard filtering for tasks, chats, and SSH sessions.',
  '2026-04-16T18:40:00.000Z',
  '2026-04-16T19:10:00.000Z',
  'demo-workspace-webapp',
  'anthropic',
  'claude-sonnet-4.5',
  '',
  '{"mode":"same-as-task"}',
  6,
  10,
  NULL,
  '<promise>COMPLETE</promise>$',
  'feat/',
  'dashboard',
  'main',
  1,
  0,
  1,
  1,
  0,
  0,
  'task',
  'planning',
  0,
  '2026-04-16T18:41:00.000Z',
  NULL,
  '2026-04-16T19:10:00.000Z',
  'sess-demo-plan-1',
  'http://localhost:7777',
  NULL,
  NULL,
  NULL,
  'main',
  'feat/dashboard-filters',
  '/worktrees/demo-storefront/dashboard-filters',
  '[]',
  '[{"iteration":1,"startedAt":"2026-04-16T18:42:00.000Z","completedAt":"2026-04-16T18:54:00.000Z","messageCount":4,"toolCallCount":3,"outcome":"plan_ready"}]',
  '[{"id":"log-demo-task-planning-1","level":"info","message":"Plan draft ready for review.","timestamp":"2026-04-16T18:54:00.000Z"},{"id":"log-demo-task-planning-2","level":"agent","message":"Waiting for plan approval.","timestamp":"2026-04-16T19:10:00.000Z"}]',
  '[{"id":"msg-demo-task-planning-1","role":"user","content":"Add filtering controls to the dashboard.","timestamp":"2026-04-16T18:41:00.000Z"},{"id":"msg-demo-task-planning-2","role":"assistant","content":"Plan ready. Add a compact filter bar and persist the selected query in the URL.","timestamp":"2026-04-16T18:54:00.000Z"}]',
  '[{"id":"tool-demo-task-planning-1","name":"Glob","input":{"pattern":"src/components/**/*.tsx"},"output":["src/components/dashboard.tsx"],"status":"completed","timestamp":"2026-04-16T18:45:00.000Z"}]',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  1,
  'sess-demo-plan-1',
  'http://localhost:7777',
  2,
  '# Plan
1. Add a compact filter bar.
2. Filter tasks, chats, and sessions consistently.
3. Persist the selection for refresh recovery.

PLAN_READY',
  1,
  1,
  NULL,
  NULL,
  NULL,
  NULL,
  0
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  directory = excluded.directory,
  prompt = excluded.prompt,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  workspace_id = excluded.workspace_id,
  model_provider_id = excluded.model_provider_id,
  model_model_id = excluded.model_model_id,
  model_variant = excluded.model_variant,
  cheap_model = excluded.cheap_model,
  max_iterations = excluded.max_iterations,
  max_consecutive_errors = excluded.max_consecutive_errors,
  activity_timeout_seconds = excluded.activity_timeout_seconds,
  stop_pattern = excluded.stop_pattern,
  git_branch_prefix = excluded.git_branch_prefix,
  git_commit_scope = excluded.git_commit_scope,
  base_branch = excluded.base_branch,
  use_worktree = excluded.use_worktree,
  clear_planning_folder = excluded.clear_planning_folder,
  plan_mode = excluded.plan_mode,
  plan_mode_auto_reply = excluded.plan_mode_auto_reply,
  auto_accept_plan = excluded.auto_accept_plan,
  fully_autonomous = excluded.fully_autonomous,
  mode = excluded.mode,
  status = excluded.status,
  current_iteration = excluded.current_iteration,
  started_at = excluded.started_at,
  completed_at = excluded.completed_at,
  last_activity_at = excluded.last_activity_at,
  session_id = excluded.session_id,
  session_server_url = excluded.session_server_url,
  error_message = excluded.error_message,
  error_iteration = excluded.error_iteration,
  error_timestamp = excluded.error_timestamp,
  git_original_branch = excluded.git_original_branch,
  git_working_branch = excluded.git_working_branch,
  git_worktree_path = excluded.git_worktree_path,
  git_commits = excluded.git_commits,
  recent_iterations = excluded.recent_iterations,
  logs = excluded.logs,
  messages = excluded.messages,
  tool_calls = excluded.tool_calls,
  consecutive_errors = excluded.consecutive_errors,
  pending_prompt = excluded.pending_prompt,
  pending_model_provider_id = excluded.pending_model_provider_id,
  pending_model_model_id = excluded.pending_model_model_id,
  pending_model_variant = excluded.pending_model_variant,
  plan_mode_active = excluded.plan_mode_active,
  plan_session_id = excluded.plan_session_id,
  plan_server_url = excluded.plan_server_url,
  plan_feedback_rounds = excluded.plan_feedback_rounds,
  plan_content = excluded.plan_content,
  planning_folder_cleared = excluded.planning_folder_cleared,
  plan_is_ready = excluded.plan_is_ready,
  pending_plan_question = excluded.pending_plan_question,
  review_mode = excluded.review_mode,
  pull_request_monitoring = excluded.pull_request_monitoring,
  automatic_pr_flow = excluded.automatic_pr_flow,
  fully_autonomous_pending = excluded.fully_autonomous_pending;

INSERT INTO tasks (
  id,
  name,
  directory,
  prompt,
  created_at,
  updated_at,
  workspace_id,
  model_provider_id,
  model_model_id,
  model_variant,
  cheap_model,
  max_iterations,
  max_consecutive_errors,
  activity_timeout_seconds,
  stop_pattern,
  git_branch_prefix,
  git_commit_scope,
  base_branch,
  use_worktree,
  clear_planning_folder,
  plan_mode,
  plan_mode_auto_reply,
  auto_accept_plan,
  fully_autonomous,
  mode,
  status,
  current_iteration,
  started_at,
  completed_at,
  last_activity_at,
  session_id,
  session_server_url,
  error_message,
  error_iteration,
  error_timestamp,
  git_original_branch,
  git_working_branch,
  git_worktree_path,
  git_commits,
  recent_iterations,
  logs,
  messages,
  tool_calls,
  consecutive_errors,
  pending_prompt,
  pending_model_provider_id,
  pending_model_model_id,
  pending_model_variant,
  plan_mode_active,
  plan_session_id,
  plan_server_url,
  plan_feedback_rounds,
  plan_content,
  planning_folder_cleared,
  plan_is_ready,
  pending_plan_question,
  review_mode,
  pull_request_monitoring,
  automatic_pr_flow,
  fully_autonomous_pending
) VALUES (
  'demo-task-running',
  'Rework invoice timeline',
  '/srv/workspaces/billing-api',
  'Improve the invoice timeline with grouped events and cleaner empty states.',
  '2026-04-16T18:50:00.000Z',
  '2026-04-16T19:33:00.000Z',
  'demo-workspace-api',
  'openai',
  'gpt-5.2',
  '',
  '{"mode":"custom","model":{"providerID":"openai","modelID":"gpt-5-mini","variant":""}}',
  8,
  10,
  NULL,
  '<promise>COMPLETE</promise>$',
  'feat/',
  'billing',
  'main',
  1,
  0,
  0,
  1,
  0,
  0,
  'task',
  'completed',
  3,
  '2026-04-16T18:52:00.000Z',
  '2026-04-16T19:34:00.000Z',
  '2026-04-16T19:33:00.000Z',
  'sess-demo-running-1',
  'http://demo-agent.internal:7777',
  NULL,
  NULL,
  NULL,
  'main',
  'feat/invoice-timeline',
  '/srv/worktrees/billing-api/running-task',
  '[{"iteration":1,"sha":"abc1234","message":"feat(billing): scaffold grouped timeline","timestamp":"2026-04-16T19:01:00.000Z","filesChanged":4},{"iteration":2,"sha":"def5678","message":"refactor(billing): extract empty state cards","timestamp":"2026-04-16T19:18:00.000Z","filesChanged":6}]',
  '[{"iteration":1,"startedAt":"2026-04-16T18:52:00.000Z","completedAt":"2026-04-16T19:01:00.000Z","messageCount":6,"toolCallCount":4,"outcome":"continue"},{"iteration":2,"startedAt":"2026-04-16T19:05:00.000Z","completedAt":"2026-04-16T19:18:00.000Z","messageCount":5,"toolCallCount":6,"outcome":"continue"}]',
  '[{"id":"log-demo-task-running-1","level":"info","message":"Connected to remote workspace host.","timestamp":"2026-04-16T18:52:10.000Z"},{"id":"log-demo-task-running-2","level":"agent","message":"Refined grouped event rendering.","timestamp":"2026-04-16T19:22:00.000Z"},{"id":"log-demo-task-running-3","level":"info","message":"Demo task completed successfully.","timestamp":"2026-04-16T19:34:00.000Z"}]',
  '[{"id":"msg-demo-task-running-1","role":"user","content":"Make the invoice timeline easier to scan.","timestamp":"2026-04-16T18:52:00.000Z"},{"id":"msg-demo-task-running-2","role":"assistant","content":"I grouped related events and tightened the spacing.","timestamp":"2026-04-16T19:22:30.000Z"}]',
  '[{"id":"tool-demo-task-running-1","name":"Read","input":{"filePath":"src/components/invoice-timeline.tsx"},"output":{"lineCount":280},"status":"completed","timestamp":"2026-04-16T18:57:00.000Z"},{"id":"tool-demo-task-running-2","name":"Edit","input":{"filePath":"src/components/invoice-timeline.tsx"},"output":{"updated":true},"status":"completed","timestamp":"2026-04-16T19:20:00.000Z"}]',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  0,
  NULL,
  NULL,
  0,
  NULL,
  0,
  0,
  NULL,
  NULL,
  NULL,
  NULL,
  0
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  directory = excluded.directory,
  prompt = excluded.prompt,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  workspace_id = excluded.workspace_id,
  model_provider_id = excluded.model_provider_id,
  model_model_id = excluded.model_model_id,
  model_variant = excluded.model_variant,
  cheap_model = excluded.cheap_model,
  max_iterations = excluded.max_iterations,
  max_consecutive_errors = excluded.max_consecutive_errors,
  activity_timeout_seconds = excluded.activity_timeout_seconds,
  stop_pattern = excluded.stop_pattern,
  git_branch_prefix = excluded.git_branch_prefix,
  git_commit_scope = excluded.git_commit_scope,
  base_branch = excluded.base_branch,
  use_worktree = excluded.use_worktree,
  clear_planning_folder = excluded.clear_planning_folder,
  plan_mode = excluded.plan_mode,
  plan_mode_auto_reply = excluded.plan_mode_auto_reply,
  auto_accept_plan = excluded.auto_accept_plan,
  fully_autonomous = excluded.fully_autonomous,
  mode = excluded.mode,
  status = excluded.status,
  current_iteration = excluded.current_iteration,
  started_at = excluded.started_at,
  completed_at = excluded.completed_at,
  last_activity_at = excluded.last_activity_at,
  session_id = excluded.session_id,
  session_server_url = excluded.session_server_url,
  error_message = excluded.error_message,
  error_iteration = excluded.error_iteration,
  error_timestamp = excluded.error_timestamp,
  git_original_branch = excluded.git_original_branch,
  git_working_branch = excluded.git_working_branch,
  git_worktree_path = excluded.git_worktree_path,
  git_commits = excluded.git_commits,
  recent_iterations = excluded.recent_iterations,
  logs = excluded.logs,
  messages = excluded.messages,
  tool_calls = excluded.tool_calls,
  consecutive_errors = excluded.consecutive_errors,
  pending_prompt = excluded.pending_prompt,
  pending_model_provider_id = excluded.pending_model_provider_id,
  pending_model_model_id = excluded.pending_model_model_id,
  pending_model_variant = excluded.pending_model_variant,
  plan_mode_active = excluded.plan_mode_active,
  plan_session_id = excluded.plan_session_id,
  plan_server_url = excluded.plan_server_url,
  plan_feedback_rounds = excluded.plan_feedback_rounds,
  plan_content = excluded.plan_content,
  planning_folder_cleared = excluded.planning_folder_cleared,
  plan_is_ready = excluded.plan_is_ready,
  pending_plan_question = excluded.pending_plan_question,
  review_mode = excluded.review_mode,
  pull_request_monitoring = excluded.pull_request_monitoring,
  automatic_pr_flow = excluded.automatic_pr_flow,
  fully_autonomous_pending = excluded.fully_autonomous_pending;

INSERT INTO tasks (
  id,
  name,
  directory,
  prompt,
  created_at,
  updated_at,
  workspace_id,
  model_provider_id,
  model_model_id,
  model_variant,
  cheap_model,
  max_iterations,
  max_consecutive_errors,
  activity_timeout_seconds,
  stop_pattern,
  git_branch_prefix,
  git_commit_scope,
  base_branch,
  use_worktree,
  clear_planning_folder,
  plan_mode,
  plan_mode_auto_reply,
  auto_accept_plan,
  fully_autonomous,
  mode,
  status,
  current_iteration,
  started_at,
  completed_at,
  last_activity_at,
  session_id,
  session_server_url,
  error_message,
  error_iteration,
  error_timestamp,
  git_original_branch,
  git_working_branch,
  git_worktree_path,
  git_commits,
  recent_iterations,
  logs,
  messages,
  tool_calls,
  consecutive_errors,
  pending_prompt,
  pending_model_provider_id,
  pending_model_model_id,
  pending_model_variant,
  plan_mode_active,
  plan_session_id,
  plan_server_url,
  plan_feedback_rounds,
  plan_content,
  planning_folder_cleared,
  plan_is_ready,
  pending_plan_question,
  review_mode,
  pull_request_monitoring,
  automatic_pr_flow,
  fully_autonomous_pending
) VALUES (
  'demo-task-pushed',
  'PR follow-up automation',
  '/srv/workspaces/billing-api',
  'Handle PR feedback automatically after push and keep monitoring merge state.',
  '2026-04-16T17:40:00.000Z',
  '2026-04-16T19:28:00.000Z',
  'demo-workspace-api',
  'anthropic',
  'claude-sonnet-4.6',
  'thinking',
  '{"mode":"same-as-task"}',
  NULL,
  10,
  NULL,
  '<promise>COMPLETE</promise>$',
  'feat/',
  'automation',
  'main',
  1,
  0,
  0,
  1,
  1,
  1,
  'task',
  'pushed',
  5,
  '2026-04-16T17:42:00.000Z',
  '2026-04-16T18:50:00.000Z',
  '2026-04-16T19:28:00.000Z',
  'sess-demo-pushed-1',
  'http://demo-agent.internal:7777',
  NULL,
  NULL,
  NULL,
  'main',
  'feat/pr-automation',
  '/srv/worktrees/billing-api/pr-automation',
  '[{"iteration":2,"sha":"111aaaa","message":"feat(automation): monitor pushed PR state","timestamp":"2026-04-16T18:02:00.000Z","filesChanged":5},{"iteration":4,"sha":"222bbbb","message":"feat(automation): persist handled review items","timestamp":"2026-04-16T18:34:00.000Z","filesChanged":7}]',
  '[{"iteration":1,"startedAt":"2026-04-16T17:42:00.000Z","completedAt":"2026-04-16T17:55:00.000Z","messageCount":4,"toolCallCount":3,"outcome":"continue"},{"iteration":2,"startedAt":"2026-04-16T17:57:00.000Z","completedAt":"2026-04-16T18:02:00.000Z","messageCount":3,"toolCallCount":4,"outcome":"continue"},{"iteration":3,"startedAt":"2026-04-16T18:10:00.000Z","completedAt":"2026-04-16T18:20:00.000Z","messageCount":4,"toolCallCount":2,"outcome":"continue"},{"iteration":4,"startedAt":"2026-04-16T18:25:00.000Z","completedAt":"2026-04-16T18:34:00.000Z","messageCount":5,"toolCallCount":5,"outcome":"continue"},{"iteration":5,"startedAt":"2026-04-16T18:40:00.000Z","completedAt":"2026-04-16T18:50:00.000Z","messageCount":2,"toolCallCount":1,"outcome":"complete"}]',
  '[{"id":"log-demo-task-pushed-1","level":"info","message":"Branch pushed to origin.","timestamp":"2026-04-16T18:50:00.000Z"},{"id":"log-demo-task-pushed-2","level":"info","message":"Demo PR metadata loaded without starting live monitoring.","timestamp":"2026-04-16T19:28:00.000Z"}]',
  '[{"id":"msg-demo-task-pushed-1","role":"user","content":"Monitor pushed PRs and react to review feedback.","timestamp":"2026-04-16T17:42:00.000Z"},{"id":"msg-demo-task-pushed-2","role":"assistant","content":"The branch is pushed and the PR automation task is active.","timestamp":"2026-04-16T19:28:00.000Z"}]',
  '[{"id":"tool-demo-task-pushed-1","name":"Bash","input":{"command":"gh pr view --json number,state,url"},"output":{"number":42,"state":"OPEN","url":"https://github.com/example/billing-api/pull/42"},"status":"completed","timestamp":"2026-04-16T19:05:00.000Z"}]',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  0,
  NULL,
  NULL,
  0,
  NULL,
  0,
  0,
  NULL,
  '{"addressable":false,"completionAction":"push","reviewCycles":1,"reviewBranches":[]}',
  '{"status":"open","lastCheckedAt":"2026-04-16T19:28:00.000Z","pullRequestNumber":42,"pullRequestUrl":"https://github.com/example/billing-api/pull/42"}',
  '{"enabled":false,"status":"stopped","startedAt":"2026-04-16T18:50:00.000Z","updatedAt":"2026-04-16T19:28:00.000Z","lastCheckedAt":"2026-04-16T19:28:00.000Z","pullRequestNumber":42,"pullRequestUrl":"https://github.com/example/billing-api/pull/42","handledItems":[]}',
  0
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  directory = excluded.directory,
  prompt = excluded.prompt,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  workspace_id = excluded.workspace_id,
  model_provider_id = excluded.model_provider_id,
  model_model_id = excluded.model_model_id,
  model_variant = excluded.model_variant,
  cheap_model = excluded.cheap_model,
  max_iterations = excluded.max_iterations,
  max_consecutive_errors = excluded.max_consecutive_errors,
  activity_timeout_seconds = excluded.activity_timeout_seconds,
  stop_pattern = excluded.stop_pattern,
  git_branch_prefix = excluded.git_branch_prefix,
  git_commit_scope = excluded.git_commit_scope,
  base_branch = excluded.base_branch,
  use_worktree = excluded.use_worktree,
  clear_planning_folder = excluded.clear_planning_folder,
  plan_mode = excluded.plan_mode,
  plan_mode_auto_reply = excluded.plan_mode_auto_reply,
  auto_accept_plan = excluded.auto_accept_plan,
  fully_autonomous = excluded.fully_autonomous,
  mode = excluded.mode,
  status = excluded.status,
  current_iteration = excluded.current_iteration,
  started_at = excluded.started_at,
  completed_at = excluded.completed_at,
  last_activity_at = excluded.last_activity_at,
  session_id = excluded.session_id,
  session_server_url = excluded.session_server_url,
  error_message = excluded.error_message,
  error_iteration = excluded.error_iteration,
  error_timestamp = excluded.error_timestamp,
  git_original_branch = excluded.git_original_branch,
  git_working_branch = excluded.git_working_branch,
  git_worktree_path = excluded.git_worktree_path,
  git_commits = excluded.git_commits,
  recent_iterations = excluded.recent_iterations,
  logs = excluded.logs,
  messages = excluded.messages,
  tool_calls = excluded.tool_calls,
  consecutive_errors = excluded.consecutive_errors,
  pending_prompt = excluded.pending_prompt,
  pending_model_provider_id = excluded.pending_model_provider_id,
  pending_model_model_id = excluded.pending_model_model_id,
  pending_model_variant = excluded.pending_model_variant,
  plan_mode_active = excluded.plan_mode_active,
  plan_session_id = excluded.plan_session_id,
  plan_server_url = excluded.plan_server_url,
  plan_feedback_rounds = excluded.plan_feedback_rounds,
  plan_content = excluded.plan_content,
  planning_folder_cleared = excluded.planning_folder_cleared,
  plan_is_ready = excluded.plan_is_ready,
  pending_plan_question = excluded.pending_plan_question,
  review_mode = excluded.review_mode,
  pull_request_monitoring = excluded.pull_request_monitoring,
  automatic_pr_flow = excluded.automatic_pr_flow,
  fully_autonomous_pending = excluded.fully_autonomous_pending;

INSERT INTO tasks (
  id,
  name,
  directory,
  prompt,
  created_at,
  updated_at,
  workspace_id,
  model_provider_id,
  model_model_id,
  model_variant,
  cheap_model,
  max_iterations,
  max_consecutive_errors,
  activity_timeout_seconds,
  stop_pattern,
  git_branch_prefix,
  git_commit_scope,
  base_branch,
  use_worktree,
  clear_planning_folder,
  plan_mode,
  plan_mode_auto_reply,
  auto_accept_plan,
  fully_autonomous,
  mode,
  status,
  current_iteration,
  started_at,
  completed_at,
  last_activity_at,
  session_id,
  session_server_url,
  error_message,
  error_iteration,
  error_timestamp,
  git_original_branch,
  git_working_branch,
  git_worktree_path,
  git_commits,
  recent_iterations,
  logs,
  messages,
  tool_calls,
  consecutive_errors,
  pending_prompt,
  pending_model_provider_id,
  pending_model_model_id,
  pending_model_variant,
  plan_mode_active,
  plan_session_id,
  plan_server_url,
  plan_feedback_rounds,
  plan_content,
  planning_folder_cleared,
  plan_is_ready,
  pending_plan_question,
  review_mode,
  pull_request_monitoring,
  automatic_pr_flow,
  fully_autonomous_pending
) VALUES (
  'demo-task-failed',
  'Sync legacy ledger jobs',
  '/workspaces/demo-storefront',
  'Backfill ledger jobs from the old worker system and remove dead code.',
  '2026-04-16T17:20:00.000Z',
  '2026-04-16T18:12:00.000Z',
  'demo-workspace-webapp',
  'anthropic',
  'claude-sonnet-4.5',
  '',
  '{"mode":"same-as-task"}',
  5,
  10,
  NULL,
  '<promise>COMPLETE</promise>$',
  'chore/',
  'ledger',
  'main',
  1,
  0,
  0,
  1,
  0,
  0,
  'task',
  'failed',
  2,
  '2026-04-16T17:25:00.000Z',
  '2026-04-16T18:12:00.000Z',
  '2026-04-16T18:12:00.000Z',
  'sess-demo-failed-1',
  'http://localhost:7777',
  'Migration script could not parse the legacy payload.',
  2,
  '2026-04-16T18:12:00.000Z',
  'main',
  'chore/ledger-sync',
  '/worktrees/demo-storefront/ledger-sync',
  '[{"iteration":1,"sha":"fedcba1","message":"chore(ledger): add migration scaffold","timestamp":"2026-04-16T17:45:00.000Z","filesChanged":3}]',
  '[{"iteration":1,"startedAt":"2026-04-16T17:25:00.000Z","completedAt":"2026-04-16T17:45:00.000Z","messageCount":4,"toolCallCount":2,"outcome":"continue"},{"iteration":2,"startedAt":"2026-04-16T17:50:00.000Z","completedAt":"2026-04-16T18:12:00.000Z","messageCount":3,"toolCallCount":4,"outcome":"error"}]',
  '[{"id":"log-demo-task-failed-1","level":"warn","message":"Legacy payload parser returned an unexpected shape.","timestamp":"2026-04-16T18:08:00.000Z"},{"id":"log-demo-task-failed-2","level":"error","message":"Task failed after repeated parser errors.","timestamp":"2026-04-16T18:12:00.000Z"}]',
  '[{"id":"msg-demo-task-failed-1","role":"user","content":"Migrate the old ledger job payloads.","timestamp":"2026-04-16T17:25:00.000Z"},{"id":"msg-demo-task-failed-2","role":"assistant","content":"The legacy payload format is inconsistent and needs manual cleanup.","timestamp":"2026-04-16T18:12:00.000Z"}]',
  '[{"id":"tool-demo-task-failed-1","name":"Bash","input":{"command":"bun run scripts/migrate-ledger.ts"},"output":{"exitCode":1,"stderr":"Unexpected token at row 19"},"status":"failed","timestamp":"2026-04-16T18:12:00.000Z"}]',
  '{"lastErrorMessage":"Unexpected token at row 19","count":2}',
  NULL,
  NULL,
  NULL,
  NULL,
  0,
  NULL,
  NULL,
  0,
  NULL,
  0,
  0,
  NULL,
  NULL,
  NULL,
  NULL,
  0
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  directory = excluded.directory,
  prompt = excluded.prompt,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  workspace_id = excluded.workspace_id,
  model_provider_id = excluded.model_provider_id,
  model_model_id = excluded.model_model_id,
  model_variant = excluded.model_variant,
  cheap_model = excluded.cheap_model,
  max_iterations = excluded.max_iterations,
  max_consecutive_errors = excluded.max_consecutive_errors,
  activity_timeout_seconds = excluded.activity_timeout_seconds,
  stop_pattern = excluded.stop_pattern,
  git_branch_prefix = excluded.git_branch_prefix,
  git_commit_scope = excluded.git_commit_scope,
  base_branch = excluded.base_branch,
  use_worktree = excluded.use_worktree,
  clear_planning_folder = excluded.clear_planning_folder,
  plan_mode = excluded.plan_mode,
  plan_mode_auto_reply = excluded.plan_mode_auto_reply,
  auto_accept_plan = excluded.auto_accept_plan,
  fully_autonomous = excluded.fully_autonomous,
  mode = excluded.mode,
  status = excluded.status,
  current_iteration = excluded.current_iteration,
  started_at = excluded.started_at,
  completed_at = excluded.completed_at,
  last_activity_at = excluded.last_activity_at,
  session_id = excluded.session_id,
  session_server_url = excluded.session_server_url,
  error_message = excluded.error_message,
  error_iteration = excluded.error_iteration,
  error_timestamp = excluded.error_timestamp,
  git_original_branch = excluded.git_original_branch,
  git_working_branch = excluded.git_working_branch,
  git_worktree_path = excluded.git_worktree_path,
  git_commits = excluded.git_commits,
  recent_iterations = excluded.recent_iterations,
  logs = excluded.logs,
  messages = excluded.messages,
  tool_calls = excluded.tool_calls,
  consecutive_errors = excluded.consecutive_errors,
  pending_prompt = excluded.pending_prompt,
  pending_model_provider_id = excluded.pending_model_provider_id,
  pending_model_model_id = excluded.pending_model_model_id,
  pending_model_variant = excluded.pending_model_variant,
  plan_mode_active = excluded.plan_mode_active,
  plan_session_id = excluded.plan_session_id,
  plan_server_url = excluded.plan_server_url,
  plan_feedback_rounds = excluded.plan_feedback_rounds,
  plan_content = excluded.plan_content,
  planning_folder_cleared = excluded.planning_folder_cleared,
  plan_is_ready = excluded.plan_is_ready,
  pending_plan_question = excluded.pending_plan_question,
  review_mode = excluded.review_mode,
  pull_request_monitoring = excluded.pull_request_monitoring,
  automatic_pr_flow = excluded.automatic_pr_flow,
  fully_autonomous_pending = excluded.fully_autonomous_pending;

INSERT INTO chats (
  id,
  name,
  workspace_id,
  directory,
  created_at,
  updated_at,
  model_provider_id,
  model_model_id,
  model_variant,
  use_worktree,
  base_branch,
  mode,
  status,
  started_at,
  completed_at,
  last_activity_at,
  session_id,
  session_server_url,
  error_message,
  error_timestamp,
  error_code,
  worktree_original_branch,
  worktree_working_branch,
  worktree_path,
  messages,
  logs,
  tool_calls,
  active_message_id,
  interrupt_requested
) VALUES (
  'demo-chat-streaming',
  'API pairing session',
  'demo-workspace-api',
  '/srv/workspaces/billing-api',
  '2026-04-16T19:00:00.000Z',
  '2026-04-16T19:34:00.000Z',
  'openai',
  'gpt-5.2',
  '',
  1,
  'main',
  'chat',
  'streaming',
  '2026-04-16T19:01:00.000Z',
  NULL,
  '2026-04-16T19:34:00.000Z',
  'chat-sess-demo-1',
  'http://demo-agent.internal:7777',
  NULL,
  NULL,
  NULL,
  'main',
  'chat/api-pairing-session',
  '/srv/worktrees/billing-api/chat-api-pairing',
  '[{"id":"msg-demo-chat-streaming-1","role":"user","content":"Review the invoice timeline API responses.","timestamp":"2026-04-16T19:01:00.000Z"},{"id":"msg-demo-chat-streaming-2","role":"assistant","content":"I found duplicated event shapes between settled and pending invoices.","timestamp":"2026-04-16T19:14:00.000Z"}]',
  '[{"id":"log-demo-chat-streaming-1","level":"info","message":"Chat session connected.","timestamp":"2026-04-16T19:01:10.000Z"},{"id":"log-demo-chat-streaming-2","level":"agent","message":"Inspecting timeline serializers.","timestamp":"2026-04-16T19:34:00.000Z"}]',
  '[{"id":"tool-demo-chat-streaming-1","name":"Read","input":{"filePath":"src/api/invoices.ts"},"output":{"lineCount":142},"status":"completed","timestamp":"2026-04-16T19:08:00.000Z"}]',
  'msg-demo-chat-streaming-2',
  0
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  workspace_id = excluded.workspace_id,
  directory = excluded.directory,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  model_provider_id = excluded.model_provider_id,
  model_model_id = excluded.model_model_id,
  model_variant = excluded.model_variant,
  use_worktree = excluded.use_worktree,
  base_branch = excluded.base_branch,
  mode = excluded.mode,
  status = excluded.status,
  started_at = excluded.started_at,
  completed_at = excluded.completed_at,
  last_activity_at = excluded.last_activity_at,
  session_id = excluded.session_id,
  session_server_url = excluded.session_server_url,
  error_message = excluded.error_message,
  error_timestamp = excluded.error_timestamp,
  error_code = excluded.error_code,
  worktree_original_branch = excluded.worktree_original_branch,
  worktree_working_branch = excluded.worktree_working_branch,
  worktree_path = excluded.worktree_path,
  messages = excluded.messages,
  logs = excluded.logs,
  tool_calls = excluded.tool_calls,
  active_message_id = excluded.active_message_id,
  interrupt_requested = excluded.interrupt_requested;

INSERT INTO chats (
  id,
  name,
  workspace_id,
  directory,
  created_at,
  updated_at,
  model_provider_id,
  model_model_id,
  model_variant,
  use_worktree,
  base_branch,
  mode,
  status,
  started_at,
  completed_at,
  last_activity_at,
  session_id,
  session_server_url,
  error_message,
  error_timestamp,
  error_code,
  worktree_original_branch,
  worktree_working_branch,
  worktree_path,
  messages,
  logs,
  tool_calls,
  active_message_id,
  interrupt_requested
) VALUES (
  'demo-chat-failed',
  'Frontend cleanup chat',
  'demo-workspace-webapp',
  '/workspaces/demo-storefront',
  '2026-04-16T18:05:00.000Z',
  '2026-04-16T18:45:00.000Z',
  'anthropic',
  'claude-sonnet-4.5',
  '',
  1,
  'main',
  'chat',
  'failed',
  '2026-04-16T18:06:00.000Z',
  '2026-04-16T18:45:00.000Z',
  '2026-04-16T18:45:00.000Z',
  'chat-sess-demo-2',
  'http://localhost:7777',
  'The local provider stopped responding during a long file search.',
  '2026-04-16T18:45:00.000Z',
  'provider_timeout',
  'main',
  'chat/frontend-cleanup',
  '/worktrees/demo-storefront/chat-frontend-cleanup',
  '[{"id":"msg-demo-chat-failed-1","role":"user","content":"Find duplicated button styles in the dashboard.","timestamp":"2026-04-16T18:06:00.000Z"},{"id":"msg-demo-chat-failed-2","role":"assistant","content":"I found three duplicated button variants before the provider timed out.","timestamp":"2026-04-16T18:44:00.000Z"}]',
  '[{"id":"log-demo-chat-failed-1","level":"warn","message":"Provider latency is above threshold.","timestamp":"2026-04-16T18:40:00.000Z"},{"id":"log-demo-chat-failed-2","level":"error","message":"Chat failed while waiting for the next event.","timestamp":"2026-04-16T18:45:00.000Z"}]',
  '[{"id":"tool-demo-chat-failed-1","name":"Glob","input":{"pattern":"src/components/**/*.tsx"},"output":["src/components/Button.tsx","src/components/IconButton.tsx"],"status":"completed","timestamp":"2026-04-16T18:20:00.000Z"}]',
  'msg-demo-chat-failed-2',
  0
)
ON CONFLICT(id) DO UPDATE SET
  name = excluded.name,
  workspace_id = excluded.workspace_id,
  directory = excluded.directory,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  model_provider_id = excluded.model_provider_id,
  model_model_id = excluded.model_model_id,
  model_variant = excluded.model_variant,
  use_worktree = excluded.use_worktree,
  base_branch = excluded.base_branch,
  mode = excluded.mode,
  status = excluded.status,
  started_at = excluded.started_at,
  completed_at = excluded.completed_at,
  last_activity_at = excluded.last_activity_at,
  session_id = excluded.session_id,
  session_server_url = excluded.session_server_url,
  error_message = excluded.error_message,
  error_timestamp = excluded.error_timestamp,
  error_code = excluded.error_code,
  worktree_original_branch = excluded.worktree_original_branch,
  worktree_working_branch = excluded.worktree_working_branch,
  worktree_path = excluded.worktree_path,
  messages = excluded.messages,
  logs = excluded.logs,
  tool_calls = excluded.tool_calls,
  active_message_id = excluded.active_message_id,
  interrupt_requested = excluded.interrupt_requested;

INSERT INTO review_comments (
  id,
  task_id,
  review_cycle,
  comment_text,
  created_at,
  status,
  addressed_at
) VALUES (
  'demo-review-comment-1',
  'demo-task-pushed',
  1,
  'Please split the PR monitoring badge into its own component.',
  '2026-04-16T19:12:00.000Z',
  'pending',
  NULL
)
ON CONFLICT(id) DO UPDATE SET
  task_id = excluded.task_id,
  review_cycle = excluded.review_cycle,
  comment_text = excluded.comment_text,
  created_at = excluded.created_at,
  status = excluded.status,
  addressed_at = excluded.addressed_at;

INSERT INTO preview_sessions (
  id,
  user_id,
  workspace_id,
  remote_host,
  remote_port,
  local_host,
  local_port,
  local_url,
  initial_path,
  cli_client_id,
  cli_hostname,
  created_at,
  updated_at,
  status,
  connected_at,
  closed_at,
  error_message
) VALUES (
  'demo-preview-session-1',
  'admin',
  'demo-workspace-api',
  '127.0.0.1',
  4173,
  '127.0.0.1',
  54173,
  'http://127.0.0.1:54173',
  '/',
  'demo-cli-client',
  'demo-workstation',
  '2026-04-16T19:15:00.000Z',
  '2026-04-16T19:15:30.000Z',
  'active',
  '2026-04-16T19:15:30.000Z',
  NULL,
  NULL
)
ON CONFLICT(id) DO UPDATE SET
  workspace_id = excluded.workspace_id,
  remote_host = excluded.remote_host,
  remote_port = excluded.remote_port,
  local_host = excluded.local_host,
  local_port = excluded.local_port,
  local_url = excluded.local_url,
  initial_path = excluded.initial_path,
  cli_client_id = excluded.cli_client_id,
  cli_hostname = excluded.cli_hostname,
  created_at = excluded.created_at,
  updated_at = excluded.updated_at,
  status = excluded.status,
  connected_at = excluded.connected_at,
  closed_at = excluded.closed_at,
  error_message = excluded.error_message;

COMMIT;
