/**
 * Loop type definitions for Ralph Loops Management System.
 * 
 * These types define the configuration and runtime state of Ralph Loops.
 * A Loop consists of:
 * - LoopConfig: Persistent configuration (name, prompt, settings)
 * - LoopState: Runtime state (status, iteration count, git state)
 * 
 * @module types/loop
 */

// Import and re-export model types from schema (single source of truth)
import type { CheapModelSelection, ModelConfig } from "./schemas/model";
import type { MessageImageAttachment } from "./message-attachments";
import type { ToolCallRecord } from "./tool-call";
export type { CheapModelSelection, ModelConfig };

/**
 * Configuration for a Ralph Loop.
 * 
 * This is the persistent configuration that defines how a loop behaves.
 * Created when a loop is first created and can be updated while the loop
 * is in draft status or between iterations.
 */
export interface LoopConfig {
  /** Unique identifier (UUID v4) */
  id: string;
  /** Human-readable loop name (entered by the user or generated by the UI helper before submission) */
  name: string;
  /** Absolute path to the working directory (must be a git repository) */
  directory: string;
  /** The task prompt/PRD describing what the loop should accomplish */
  prompt: string;
  /** ISO 8601 timestamp of when the loop was created */
  createdAt: string;
  /** ISO 8601 timestamp of the last configuration update */
  updatedAt: string;

  /** Workspace ID this loop belongs to */
  workspaceId: string;

  /** Model configuration for AI provider and model selection (required) */
  model: ModelConfig;

  /**
   * Optional helper-model configuration for lightweight operations such as
   * title and PR metadata generation.
   *
   * New loops persist this explicitly; legacy loops may omit it and should be
   * treated as "same as loop model".
   */
  cheapModel?: CheapModelSelection;

  /** Maximum iterations before stopping (Infinity for unlimited) */
  maxIterations: number;

  /** Maximum consecutive identical errors before failsafe exit */
  maxConsecutiveErrors: number;

  /** Seconds without events before treating as error and retrying; null for unlimited */
  activityTimeoutSeconds: number | null;

  /** Regex pattern for completion detection */
  stopPattern: string;

  /** Git integration settings for branch and commit naming */
  git: GitConfig;

  /** Base branch to create the loop from (if different from current when started) */
  baseBranch?: string;

  /** Whether the loop should run in a dedicated git worktree */
  useWorktree: boolean;

  /** Whether to clear .ralph-planning folder on start */
  clearPlanningFolder: boolean;

  /** Whether to start in plan mode (for drafts, this indicates the intended mode) */
  planMode: boolean;

  /** Whether a ready plan should be automatically accepted and executed */
  autoAcceptPlan?: boolean;

  /** Whether the accepted plan should continue through push and automatic PR flow */
  fullyAutonomous?: boolean;

  /** Mode of operation for this entity. Loops are the only supported mode. */
  mode: "loop";
}

/**
 * Git integration configuration.
 * 
 * Git is always enabled for loops. These settings control how branches
 * and commits are named for the loop's work.
 */
export interface GitConfig {
  /** Branch name prefix. Default: empty string; non-empty values are normalized to git-safe path segments (e.g., "team/" -> "team/add-auth"). */
  branchPrefix: string;
  /**
   * Conventional commit scope. Default: empty string.
   *
   * Inserted as the scope in conventional commit messages:
   * `type(scope): description` (e.g., `feat(auth): add auth endpoint`).
   *
   * Leave empty to omit the scope entirely. Generic placeholder values such as
   * `ralph` are treated as empty and omitted from generated commit messages.
   *
   * @deprecated The old `commitPrefix` field (e.g., "[Ralph]") is no longer used.
   */
  commitScope: string;
}

/**
 * Runtime state of a Ralph Loop.
 * 
 * This tracks the current execution state and is updated as the loop runs.
 * State is persisted to the database and can be restored on server restart.
 */
export interface LoopState {
  /** Same as config ID (for convenience) */
  id: string;
  /** Current execution status */
  status: LoopStatus;
  /** Number of completed iterations */
  currentIteration: number;
  /** ISO 8601 timestamp when loop was started */
  startedAt?: string;
  /** ISO 8601 timestamp when loop finished (completed, stopped, or failed) */
  completedAt?: string;
  /** ISO 8601 timestamp of the last event received */
  lastActivityAt?: string;

  /** Backend session information for the active connection */
  session?: SessionInfo;

  /** Error information if the loop failed */
  error?: LoopError;

  /** Git state tracking branches and commits */
  git?: GitState;

  /** Recent iteration summaries for display (last N iterations) */
  recentIterations: IterationSummary[];

  /** Application logs persisted for page refresh (always initialized as empty array) */
  logs: LoopLogEntry[];

  /** Messages from current iteration persisted for page refresh (always initialized as empty array) */
  messages: PersistedMessage[];

  /** Tool calls from current iteration persisted for page refresh (always initialized as empty array) */
  toolCalls: PersistedToolCall[];

  /** Consecutive error tracking for failsafe exit */
  consecutiveErrors?: ConsecutiveErrorTracker;

  /** Pending prompt that overrides config.prompt for the next iteration only */
  pendingPrompt?: string;

  /** Model override for the next prompt (one-time, cleared after use) */
  pendingModel?: ModelConfig;

  /** Plan mode state (active when status is "planning") */
  planMode?: {
    /** Whether plan mode is currently active */
    active: boolean;
    /** Session ID from plan creation (reused for execution) */
    planSessionId?: string;
    /** Server URL from plan creation */
    planServerUrl?: string;
    /** Number of feedback rounds completed */
    feedbackRounds: number;
    /** Plan content cached for display */
    planContent?: string;
    /** Whether .ralph-planning folder was already cleared (prevents re-clearing) */
    planningFolderCleared: boolean;
    /** Whether the plan is ready (PLAN_READY marker detected) */
    isPlanReady: boolean;
  };

  /** Review mode state for addressing comments after push/merge */
  reviewMode?: {
    /** Whether the loop can receive reviewer comments */
    addressable: boolean;
    /** How the loop was originally completed */
    completionAction: "push" | "merge";
    /** Number of review cycles completed */
    reviewCycles: number;
    /** List of branches created during review cycles (for merged loops) */
    reviewBranches: string[];
  };

  /** Persisted backend PR monitoring state for pushed loops */
  pullRequestMonitoring?: PullRequestMonitoringState;

  /** Persisted automatic PR flow state for pushed loops */
  automaticPrFlow?: AutomaticPrFlowState;

  /** Whether the initial fully autonomous push/PR handoff is still pending */
  fullyAutonomousPending?: boolean;

  /** Sync state for tracking branch sync during push */
  syncState?: {
    /** Current sync status */
    status: "syncing" | "clean" | "conflicts" | "resolved";
    /** The base branch being synced with */
    baseBranch: string;
    /** Whether to auto-push after conflict resolution completes */
    autoPushOnComplete: boolean;
    /** Which sync phase is in progress — working branch pull or base branch merge */
    syncPhase?: "working_branch" | "base_branch";
    /** Last local commit message to use for the merge commit */
    mergeCommitMessage?: string;
  };
}

/**
 * A persisted log entry in the loop state.
 * Stored in the database and emitted via WebSocket as loop.log events.
 */
export interface LoopLogEntry {
  /** Unique ID for the log entry (used for updates and deduplication) */
  id: string;
  /** Log level indicating the type/severity */
  level: "agent" | "user" | "info" | "warn" | "error" | "debug" | "trace";
  /** The log message content */
  message: string;
  /** Optional additional structured details */
  details?: Record<string, unknown>;
  /** ISO 8601 timestamp when the log was created */
  timestamp: string;
}

/**
 * A persisted AI message in the loop state.
 * Mirrors MessageData from events.ts for database persistence.
 */
export interface PersistedMessage {
  /** Unique message ID */
  id: string;
  /** Role: "user" for prompts, "assistant" for AI responses */
  role: "user" | "assistant";
  /** The message content */
  content: string;
  /** Inline image attachments persisted for refresh recovery when present */
  attachments?: MessageImageAttachment[];
  /** ISO 8601 timestamp when the message was created */
  timestamp: string;
}

/**
 * A persisted tool call in the loop state.
 * Mirrors ToolCallData from events.ts for database persistence.
 */
export interface PersistedToolCall extends ToolCallRecord {}

/**
 * Tracks consecutive identical errors for failsafe exit.
 * 
 * If the same error occurs consecutively more than maxConsecutiveErrors times,
 * the loop is stopped to prevent infinite error loops.
 */
export interface ConsecutiveErrorTracker {
  /** The last error message that was seen */
  lastErrorMessage: string;
  /** How many times this error has occurred consecutively */
  count: number;
}

/**
 * Possible statuses for a Ralph Loop.
 * 
 * Lifecycle: draft -> idle -> starting -> running <-> waiting -> completed/stopped/failed
 * Final states: merged, pushed, deleted (can be purged)
 */
export type LoopStatus =
  | "idle"                // Created but not started (transitional)
  | "draft"               // Saved as draft, not started (no git branch or session)
  | "planning"            // Loop is in plan creation/review mode, awaiting approval
  | "starting"            // Initializing backend connection and git branch
  | "running"             // Actively executing an iteration
  | "waiting"             // Between iterations, preparing for next
  | "completed"           // Successfully completed (stop pattern matched)
  | "stopped"             // Manually stopped by user
  | "failed"              // Unrecoverable error occurred
  | "max_iterations"      // Hit the maximum iteration limit
  | "resolving_conflicts" // Resolving merge conflicts with base branch before push
  | "merged"              // Changes merged into original branch (final state)
  | "pushed"              // Branch pushed to remote (final state, can receive reviews)
  | "deleted";            // Marked for deletion (final state, awaiting purge)

export const POST_APPROVAL_FULLY_AUTONOMOUS_EDITABLE_STATUSES: ReadonlySet<LoopStatus> = new Set([
  "starting",
  "running",
  "waiting",
  "completed",
]);

/**
 * Backend session information.
 * Tracks the connection to the agent backend.
 */
export interface SessionInfo {
  /** Backend session ID for the conversation */
  id: string;
  /** Backend server URL (for display and reconnection) */
  serverUrl?: string;
}

/**
 * Error information for a loop.
 * Stored when a loop enters failed status.
 */
export interface LoopError {
  /** Human-readable error message */
  message: string;
  /** Iteration number where the error occurred */
  iteration: number;
  /** ISO 8601 timestamp when the error occurred */
  timestamp: string;
}

/**
 * Git state for a loop.
 * Tracks the branches and commits created by the loop.
 */
export interface GitState {
  /** The branch the loop was created from */
  originalBranch: string;
  /** The branch created for this loop's work */
  workingBranch: string;
  /** Absolute path to the git worktree directory for this loop */
  worktreePath?: string;
  /** Commits made during loop execution */
  commits: GitCommit[];
}

/**
 * Git commit information.
 * Recorded each time the loop creates a commit.
 */
export interface GitCommit {
  /** Iteration number when the commit was made */
  iteration: number;
  /** Full commit SHA */
  sha: string;
  /** Commit message */
  message: string;
  /** ISO 8601 timestamp when the commit was created */
  timestamp: string;
  /** Number of files changed in this commit */
  filesChanged: number;
}

export type AutomaticPrFlowMergeStateStatus =
  | "BEHIND"
  | "BLOCKED"
  | "CLEAN"
  | "DIRTY"
  | "DRAFT"
  | "HAS_HOOKS"
  | "UNKNOWN"
  | "UNSTABLE";

export interface PullRequestBranchUpdateState {
  /** Current automatic branch-update state for a behind PR */
  status: "required" | "requested" | "conflicts" | "failed";
  /** ISO 8601 timestamp when the current behind/update state was last observed */
  lastDetectedAt: string;
  /** ISO 8601 timestamp when Ralph last triggered updateBranch() for this PR */
  lastTriggeredAt?: string;
  /** Last update-branch failure detail, when one exists */
  lastError?: string;
}

/**
 * Persisted GitHub pull request monitoring state for pushed loops.
 */
export interface PullRequestMonitoringState {
  /** Last observed monitoring state from the GitHub CLI */
  status: "unavailable" | "no_pr" | "open" | "closed" | "merged" | "error";
  /** ISO 8601 timestamp when the last probe completed */
  lastCheckedAt: string;
  /** Pull request number when one exists */
  pullRequestNumber?: number;
  /** Pull request URL when one exists */
  pullRequestUrl?: string;
  /** ISO 8601 timestamp when the PR was detected as merged */
  mergedAt?: string;
  /** Latest GitHub merge-state classification when available */
  mergeStateStatus?: AutomaticPrFlowMergeStateStatus;
  /** Whether GitHub reported that the viewer can update the PR branch */
  viewerCanUpdateBranch?: boolean;
  /** Automatic branch-update tracking while the PR is behind base */
  branchUpdate?: PullRequestBranchUpdateState;
  /** Last probe failure detail for diagnostics */
  lastError?: string;
}

/**
 * Persisted reference to a single PR feedback item handled by automation.
 */
export interface AutomaticPrFlowHandledItem {
  /** Stable GitHub identifier for the feedback item */
  id: string;
  /** Source of the feedback item */
  source: "review_thread" | "review_comment" | "review";
  /** How automation concluded the item */
  outcome: "resolved" | "ignored" | "manual";
  /** ISO 8601 timestamp when the item was recorded as handled */
  handledAt: string;
}

/**
 * Persisted state for an in-progress automated feedback batch.
 */
export interface AutomaticPrFlowActiveBatch {
  /** Unique identifier for the batch */
  batchId: string;
  /** Feedback item IDs included in this batch */
  itemIds: string[];
  /** Feedback items included in this batch */
  items: Array<{
    id: string;
    source: "review_thread" | "review_comment" | "review";
    threadId?: string;
  }>;
  /** ISO 8601 timestamp when the batch started */
  startedAt: string;
  /** Review cycle created to address this batch, when one exists */
  reviewCycle?: number;
}

/**
 * Persisted automatic PR flow state for pushed loops.
 */
export interface AutomaticPrFlowState {
  /** Whether the automatic PR flow is enabled */
  enabled: boolean;
  /** Current automation phase */
  status: "starting" | "monitoring" | "processing_feedback" | "finalizing_feedback" | "stopped" | "error";
  /** ISO 8601 timestamp when automation was enabled */
  startedAt: string;
  /** ISO 8601 timestamp when automation state was last updated */
  updatedAt: string;
  /** ISO 8601 timestamp of the last successful or attempted poll */
  lastCheckedAt?: string;
  /** Pull request number when known */
  pullRequestNumber?: number;
  /** Pull request URL when known */
  pullRequestUrl?: string;
  /** In-flight automation batch when one is being processed */
  activeBatch?: AutomaticPrFlowActiveBatch;
  /** Feedback items already handled by automation */
  handledItems: AutomaticPrFlowHandledItem[];
  /** Last automation error for diagnostics */
  lastError?: string;
  /** ISO 8601 timestamp when the user last stopped automation */
  stoppedAt?: string;
}

/**
 * Summary of a single iteration.
 * Stored in recentIterations for quick access and display.
 */
export interface IterationSummary {
  /** Iteration number (1-based) */
  iteration: number;
  /** ISO 8601 timestamp when iteration started */
  startedAt: string;
  /** ISO 8601 timestamp when iteration completed */
  completedAt: string;
  /** Number of messages exchanged in this iteration */
  messageCount: number;
  /** Number of tool calls made in this iteration */
  toolCallCount: number;
  /** How the iteration ended */
  outcome: "continue" | "complete" | "error" | "plan_ready";
}

/**
 * Combined loop configuration and state.
 * This is what the API returns for a loop.
 */
export interface Loop {
  config: LoopConfig;
  state: LoopState;
}

/**
 * Default values for loop configuration.
 */
export const DEFAULT_LOOP_CONFIG = {
  stopPattern: "<promise>COMPLETE</promise>$",
  maxIterations: Infinity,
  maxConsecutiveErrors: 10,
  activityTimeoutSeconds: null,
  useWorktree: true,
  clearPlanningFolder: false,
  planMode: true,
  autoAcceptPlan: true,
  fullyAutonomous: false,
  cheapModel: {
    mode: "same-as-loop",
  } as const,
  mode: "loop" as const,
  git: {
    branchPrefix: "",
    commitScope: "",
  },
} as const;

/**
 * Create initial state for a new loop.
 */
export function createInitialState(id: string): LoopState {
  return {
    id,
    status: "idle",
    currentIteration: 0,
    recentIterations: [],
    logs: [],
    messages: [],
    toolCalls: [],
  };
}

/**
 * Review comment for tracking feedback on completed loops.
 */
export interface ReviewComment {
  /** Unique identifier (UUID) */
  id: string;
  /** Loop ID this comment belongs to */
  loopId: string;
  /** Which review cycle this comment was submitted in */
  reviewCycle: number;
  /** The comment text */
  commentText: string;
  /** When the comment was created (ISO timestamp) */
  createdAt: string;
  /** Status: "pending" (being worked on) or "addressed" (completed) */
  status: "pending" | "addressed";
  /** When the comment was marked as addressed (ISO timestamp, null if pending) */
  addressedAt?: string;
}
