const workspaceDir = `${import.meta.dir}/..`;
const outDir = `${workspaceDir}/src/vendor`;
const outFile = `${outDir}/novnc-rfb.js`;
const entrypoint = `${workspaceDir}/node_modules/@novnc/novnc/core/rfb.js`;
const generatedHeader = `// Generated by scripts/novnc-vendor.ts from @novnc/novnc/core/rfb.js.\n// Do not edit this file directly; run \`bun run build:novnc\` instead.\n`;

export async function buildNoVncVendor(): Promise<void> {
  await Bun.$`mkdir -p ${outDir}`.quiet();
  const tempOutDir = await Bun.$`mktemp -d`.text().then((value) => value.trim());

  try {
    const result = await Bun.build({
      entrypoints: [entrypoint],
      outdir: tempOutDir,
      target: "browser",
      format: "esm",
    });

    if (!result.success) {
      const messages = result.logs.map((log) => String(log)).join("\n");
      throw new Error(messages || "Failed to build noVNC vendor bundle.");
    }

    const bundledSource = await Bun.file(`${tempOutDir}/rfb.js`).text();
    await Bun.write(outFile, `${generatedHeader}${bundledSource}`);
  } finally {
    await Bun.$`rm -rf ${tempOutDir}`.quiet();
  }
}

if (import.meta.main) {
  try {
    await buildNoVncVendor();
  } catch (error) {
    console.error(String(error));
    process.exit(1);
  }
}
