import { mkdir, mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";

const workspaceDir = resolve(import.meta.dir, "..");
const outDir = join(workspaceDir, "src", "vendor");
const outFile = join(outDir, "novnc-rfb.js");
const entrypoint = join(
  workspaceDir,
  "node_modules",
  "@novnc",
  "novnc",
  "core",
  "rfb.js",
);
const generatedHeader = `// Generated by scripts/novnc-vendor.ts from @novnc/novnc/core/rfb.js.\n// Do not edit this file directly; run \`bun run build:novnc\` instead.\n`;
const vendorReadyEnv = "CLANKY_NOVNC_VENDOR_READY";

export async function buildNoVncVendor(): Promise<void> {
  if (process.env[vendorReadyEnv] === "1" && await Bun.file(outFile).exists()) {
    return;
  }

  await mkdir(outDir, { recursive: true });
  const tempOutDir = await mkdtemp(join(tmpdir(), "clanky-novnc-"));

  try {
    const result = await Bun.build({
      entrypoints: [entrypoint],
      outdir: tempOutDir,
      target: "browser",
      format: "esm",
    });

    if (!result.success) {
      const messages = result.logs.map((log) => String(log)).join("\n");
      throw new Error(messages || "Failed to build noVNC vendor bundle.");
    }

    const bundledSource = await Bun.file(join(tempOutDir, "rfb.js")).text();
    await Bun.write(outFile, `${generatedHeader}${bundledSource}`);
  } finally {
    await rm(tempOutDir, { recursive: true, force: true });
  }
}

if (import.meta.main) {
  try {
    await buildNoVncVendor();
  } catch (error) {
    console.error(String(error));
    process.exit(1);
  }
}
